# Generated by Django 2.1.5 on 2020-03-21 04:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-c_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': '资产总表', 'verbose_name_plural': '资产总表'},
        ),
        migrations.AddField(
            model_name='asset',
            name='idc',
            field=models.CharField(max_length=128, null=True, verbose_name='所在机房'),
        ),
        migrations.AddField(
            model_name='asset',
            name='manufacturer',
            field=models.CharField(max_length=128, null=True, verbose_name='制造商'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=64, verbose_name='设备名'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_day',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 3, 21, 4, 4, 10, 271204, tzinfo=utc), null=True, verbose_name='购买日期'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='sn',
            field=models.CharField(default=uuid.uuid1, max_length=128, unique=True, verbose_name='资产序列号'),
        ),
    ]
