# Generated by Django 2.1.5 on 2020-03-21 13:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20200321_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': '设备列表', 'verbose_name_plural': '设备列表'},
        ),
        migrations.AlterField(
            model_name='asset',
            name='idc',
            field=models.CharField(max_length=128, null=True, verbose_name='实验室名'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='manufacturer',
            field=models.CharField(max_length=128, null=True, verbose_name='购置人'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_day',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 3, 21, 13, 22, 40, 210682, tzinfo=utc), null=True, verbose_name='购置日期'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='sn',
            field=models.CharField(default=uuid.uuid1, max_length=128, unique=True, verbose_name='设备ID号'),
        ),
    ]
